### PR TITLE
fix(kl-factory): add missing commands

### PR DESCRIPTION
**Pull request by SantiagoPittella**
# What ❔

* Link the command `initialize-erc20-bridge` to the `initialize-erc20-bridge.ts` script file.

## Why ❔

During the execution of the `custom-erc20-bridge` integration test to command of the `l1-contracts` are called:
https://github.com/matter-labs/zksync-era/blob/kl-factory/core/tests/ts-integration/tests/custom-erc20-bridge.test.ts#L53
```typescript
        const baseCommandL1 = isLocalSetup
            ? `yarn --cwd /contracts/l1-contracts`
            : `cd $ZKSYNC_HOME && yarn l1-contracts`;
        let args = `--private-key ${alice.privateKey} --erc20-bridge ${l1BridgeProxy.address}`;
        let command = `${baseCommandL1} initialize-erc20-bridge ${args}`;
        await spawn(command);
        await sleep(2);
        let command2 = `${baseCommandL1} erc20-deploy-on-chain ${args}`;
        await spawn(command2);
        await sleep(2);
```

The first one is an existing command. But the second, `erc20-deploy-on-chain`,  is missing.

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.

### CODE REVIEW

**Comment by SantiagoPittella** [comment]
@kelemeno do you what [this command](https://github.com/matter-labs/zksync-era/blob/kl-factory/core/tests/ts-integration/tests/custom-erc20-bridge.test.ts#L60) should be? Or where can I find it?

**Comment by kelemeno** [comment]
It has been replaced by   l2-contracts  "deploy-shared-bridge-on-l2-through-l1"

**Comment by SantiagoPittella** [comment]
> It has been replaced by l2-contracts "deploy-shared-bridge-on-l2-through-l1"

Thanks! I will continue with this then.

**Comment by juan518munoz** [comment]
@kelemeno 

Seeing that `initialize-erc20-bridge` is [_disabled_](https://github.com/matter-labs/era-contracts/blob/c43cf9710ddad71cfb8bfce6729de8199d791e4f/l1-contracts/scripts/initialize-erc20-bridge.ts#L54) and `erc20-deploy-on-chain` was replaced by `deploy-shared-bridge-on-l2-through-l1`, what should be the new procedure for this test?

**Pull request closed without merging**
