### PR TITLE
feat(l1): added missing foundry lib symlinks

### PR DESCRIPTION
**Pull request by benceharomi**
# What ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.

### CODE REVIEW

**Comment by StanislavBreadless** [comment]
@benceharomi this pr (https://github.com/matter-labs/era-contracts/pull/740) is more broad for making dev work with the server

**Comment by StanislavBreadless** [comment]
ah it actually introduces less symlinks...

**Comment by benceharomi** [comment]
@StanislavBreadless I added all needed symlinks and also removed `node_modules` from the foundry config, because it was unknown whether some modules were imported from the the `lib` dir or from `node_modules` and it was too confusing.
It is better to use the `lib` deps for foundry and `node_modules` for harhdat.

**Comment by benceharomi** [comment]
> @benceharomi this pr (#740) is more broad for making dev work with the server

are the `allow_paths` and the `fs_permissions` actually required in the `foundry.toml`? For me both the build and tests worked without those.

Can you tell me where do we need them? @StanislavBreadless

**Comment by StanislavBreadless** [comment]
for me personally tests did not run without those, but maybe there was a different reason

**Comment by benceharomi** [comment]
> for me personally tests did not run without those, but maybe there was a different reason

I leave those parts in, updated the PR accordingly.

Remaining changes:
* added missing symlinks
* removed `node_modules` from foundry libs

**Review by StanislavBreadless — APPROVED** [review]

**Pull request merged**
