### PR TITLE
fix(Validium): Get rid of needing solpp for preprocessing `Executor.sol`

### PR DESCRIPTION
**Pull request by ilitteri**
# What ❔

Get rid of needing solpp for preprocessing `Executor.sol` differently depending on which local mode is set.

## Why ❔

`era-contracts` repo has native support for Validium already, so there is no need to use the preprocessor.

Links for reference:

- https://github.com/matter-labs/era-contracts/blob/main/l1-contracts/contracts/zksync/Storage.sol#L172C15-L172C24
- https://github.com/matter-labs/era-contracts/blob/main/l1-contracts/contracts/zksync/Storage.sol#L90
- https://github.com/matter-labs/era-contracts/blob/main/l1-contracts/contracts/zksync/Storage.sol#L78

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.

### CODE REVIEW

**Review by popzxc — COMMENTED** [review]
I guess this PR was superseded by https://github.com/matter-labs/era-contracts/pull/225 and thus can be closed?

**Comment by ilitteri** [comment]
> I guess this PR was superseded by #225 and thus can be closed?

Indeed, I think I mischoose #225 base branch (it should be this PR's).

**Comment by popzxc** [comment]
@ilitteri yeah, let's close this PR and do everything in #225

**Comment by ilitteri** [comment]
Superseded by #225

**Pull request closed without merging**
